### ISSUE TITLE
Needs more examples of blade use. 

### ISSUE THREAD

**Issue by musiccollect** [scaventum/tabwire#1]
Need more explanation on this usage:

<div>@include('tabwire::components.contents', ['tabs' => $tabs])</div>

Leaving that line as is causes error "View [components.contents] not found".

Changing components.contents to any view name has same result.

**Comment by scaventum** [comment]
Hi, thanks for your feedback. Looks like the doc is wrong here. Can you try `tabwire::components.content` without the (s)? e.g.:
```
@include('tabwire::components.content', ['tabs' => $tabs])
```
